apps/dashboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # Views
    path('', main, name='main'),
    path('home/', home, name='home'),
    path('events/', calendar_view, name='events'),
    path('kpi-view/', kpi_view, name='kpi-view'),
    path('report-view/', report_view, name='report-view'),
    path('export-report/', export_report_to_excel, name='export-report'),
    
    # Lists
    path('operator-list/', operator_list, name='operator-list'),
    path('teacher-list/', teacher_list, name='teacher-list'),
    path('pupil-list/', pupil_list, name='pupil-list'),
    path('lesson-list/<str:pk>/', lesson_list, name='lesson-list'),
    path('group-list/', group_list, name='group-list'),
    path('course-list/', course_list, name='course-list'),
    path('room-list/', room_list, name='room-list'),
    path('support-list/', support_list, name='support-list'),

    # Details
    path('group-detail/<str:pk>/', group_detail, name='group-detail'),
    path('course-detail/<str:pk>/', course_detail, name='course-detail'),
    path('lesson-detail/<str:pk>/', lesson_detail, name='lesson-detail'),
    path('room-detail/<str:pk>/', room_detail, name='room-detail'),

    # Create
    path('lesson-create/<str:pk>/', lesson_create, name='lesson-create'),

    # Update
    path('lesson-update/<str:pk>/', lesson_update, name='lesson-update'),
    path('group-update/<str:pk>/', group_update, name='group-update'),
    path('course-update/<str:pk>/', course_update, name='course-update'),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.dashboard.urls')),
    path('account/', include('apps.user.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/dashboard/models.py
from django.db import models

class WeekDays(models.Model):
    title = models.CharField(max_length=50)
    day_number = models.IntegerField(null=True)
    def __str__(self):
        return self.title

class Course(models.Model):
    image = models.ImageField(upload_to='course_images/', null=True)
    title = models.CharField(max_length=140)
    DURATION = (
        ('30', '30 мин'),
        ('40', '40 мин'),
        ('50', '50 мин'),
        ('60', '60 мин'),
        ('70', '70 мин'),
        ('80', '80 мин'),
    )
    duration = models.CharField(max_length=4, null=True, choices=DURATION)
    price = models.IntegerField(null=True)

    def __str__(self):
        return self.title
    

class Room(models.Model):
    title = models.CharField(max_length=40)

    def __str__(self):
        return self.title


class Group(models.Model):
    title = models.CharField(max_length=40)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    days = models.ManyToManyField(WeekDays)
    color = models.CharField(max_length=10, null=True, default='#10D5D2')
    start_time = models.TimeField(auto_now_add=False, null=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)

    @property
    def group_pupil_percentage(self):
        total_pupils = self.pupil_set.count()
        total_percentage = sum([pupil.total_percentage for pupil in self.pupil_set.all()])
        
        return round(total_percentage / total_pupils) if total_pupils else 0

    def __str__(self):
        return self.title


class Support(models.Model):
    name = models.CharField(max_length=20)
    phone = models.IntegerField()
    whatsapp = models.IntegerField()
    is_called = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

apps/user/models.py
from django.db import models
from apps.dashboard.models import Group, Course
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=140, null=True)
    STATUS = (
        ('1', 'Админ'),
        ('2', 'Студент'),
        ('3', 'Преподаватель'),
        ('4', 'Администратор')
    )
    role = models.CharField(null=True, choices=STATUS, max_length=140, default='1')
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []


class Lesson(models.Model):
    title = models.CharField(max_length=140)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    group_access = models.ManyToManyField(Group, blank=True)
    content = models.TextField(null=True, blank=True)
    access = models.BooleanField(null=True, blank=True, default=False)


    
    def __str__(self):
        return self.title


class Question(models.Model):
    lesson=models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True, blank=True)
    SKILLS = (
        ('vocabulary', 'Vocabulary'),
        ('grammary', 'Grammary'),
        ('speaking', 'Speaking'),
        ('reading', 'Reading'),
        ('listening', 'Listening'),
    )
    skill = models.CharField(max_length=80, null=True, choices=SKILLS)
    title = models.CharField(max_length=150, null=True)
    marks=models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=20, null=True)
    is_correct = models.BooleanField(default=False ,verbose_name='Правильно')

    def __str__(self):
        return self.title


class TestResult(models.Model):
    pupil = models.ForeignKey('Pupil', on_delete=models.CASCADE, null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True)
    questions = models.ManyToManyField(Question)
    total_correct_answers = models.IntegerField(null=True)
    total_questions = models.IntegerField(null=True)
    
    vocabulary_score = models.IntegerField(null=True, blank=True, default='0')
    listening_score = models.IntegerField(null=True, blank=True, default='0')
    reading_score = models.IntegerField(null=True, blank=True, default='0')
    grammary_score = models.IntegerField(null=True, blank=True, default='0')
    speaking_score = models.IntegerField(null=True, blank=True, default='0')


    def __str__(self):
        return self.pupil.name


class Operator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='profile_photos', null=True, blank=True)
    phone = models.CharField(max_length=12, default='996')
    group = models.ManyToManyField(Group)
    password = models.CharField(max_length=20, null=True, default=' ')

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='profile_photos', null=True, blank=True)
    phone = models.CharField(max_length=12, default='996')
    group = models.ManyToManyField(Group)
    payment = models.IntegerField(null=True)
    password = models.CharField(max_length=20, null=True, default=' ')

    def __str__(self):
        return self.name

    @property
    def group_pupil_percentage(self):
        total_pupils = 0
        total_percentage = 0
        
        for group in self.group.all():
            pupils = group.pupil_set.all()
            total_pupils += len(pupils)
            total_percentage += sum([pupil.total_percentage for pupil in pupils])
        
        return round(total_percentage / total_pupils) if total_pupils else 0

class Pupil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='profile_photos', null=True, blank=True)
    phone = models.CharField(max_length=12, default='996')
    group = models.ManyToManyField(Group)
    password = models.CharField(max_length=20, null=True, default=' ')


    def __str__(self):
        return self.name
    

    @property
    def total_amount(self):
        transactions = self.transaction_set.all()
        total = sum([item.amount for item in transactions])
        return total
    
    @property
    def total_score(self):
        answers = self.testresult_set.all()
        total = sum([item.total_correct_answers for item in answers])
        return total
    
    @property
    def total_questions(self):
        questions = self.testresult_set.all()
        total = sum([item.total_questions for item in questions])
        return total
    
    @property
    def total_percentage(self):
        try:
            return round((self.total_score / self.total_questions) * 100)
        except:
            return  0

    def skill_percentage(self, skill):
        skill_questions = TestResult.objects.filter(
            pupil=self,
            questions__skill=skill
        ).count()
        correct_answers = TestResult.objects.filter(pupil=self)
        total_score = sum(getattr(item, f'{skill}_score') for item in correct_answers)

        if skill_questions != 0:
            skill_percentage = (total_score / skill_questions) * 100
        else:
            skill_percentage = 0

        return round(skill_percentage)

    @property
    def vocabulary_percentage(self):
        return self.skill_percentage('vocabulary')

    @property
    def grammary_percentage(self):
        return self.skill_percentage('grammary')

    @property
    def reading_percentage(self):
        return self.skill_percentage('reading')

    @property
    def speaking_percentage(self):
        return self.skill_percentage('speaking')

    @property
    def listening_percentage(self):
        return self.skill_percentage('listening')


class Attendance(models.Model):
    pupils = models.ManyToManyField(Pupil)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.lesson.title} ({self.date})'


class Transaction(models.Model):
    pupil = models.ForeignKey(Pupil, on_delete=models.SET_NULL, null=True)
    amount = models.IntegerField()
    comment = models.TextField(max_length=140)
    created = models.DateField(auto_now_add=False)


class Report(models.Model):
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE, null=True)
    TYPE = (
        ('plus', 'Приход'),
        ('minus', 'Расход')
    )

    title = models.CharField(max_length=140)
    price = models.FloatField()
    type = models.CharField(choices=TYPE, max_length=40)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

templates/dashboard/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="modal fade" id="basicModal" tabindex="-1" style="display: none;" aria-modal="true" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel1">Удаление курса</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <span>Вы действительно хотите удалить этот курс?</span>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Отмена</button>
                  <form action="" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" name="delete">Удалить</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="nav nav-pills flex-column flex-md-row mb-3">
                    <li class="nav-item"><a class="nav-link active" href="javascript:void(0);"><i
                                class="bx bx-user me-1"></i>Курс</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'lesson-list' course.id %}"><i class='bx bx-group'></i> Уроки</a></li>
                </ul>
                <div class="row">
                    <div class="col-md-6 col-lg-4 order-1 mb-4">
                        <div class="card">
                          <div class="card-header d-flex align-items-center justify-content-between">
                            <h5 class="card-title m-0 me-2">Информация о курсе</h5>
                            <div class="dropdown">
                                <button class="btn p-0" type="button" id="transactionID" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  <i class="bx bx-dots-vertical-rounded"></i>
                                </button>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="transactionID">
                                  <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#basicModal">
                                    Удалить
                                  </button>
                                  
                                  <a class="dropdown-item" href="{% url 'course-update' course.id %}">Изменить</a>
                                </div>
                              </div>
                          </div>
                          <div class="card-body">
                            <ul class="p-0 m-0">
                                <small class="text-muted d-block mb-1">Название</small>
                                <div class="me-2 mb-2">
                                    <span class="mb-0">{{ course.title }}</span>
                                </div>
                                <small class="text-muted d-block mb-1">Цена</small>
                                <div class="me-2 mb-2">
                                    <span class="mb-0">{{ course.price }}с</span>
                                </div>
                                <small class="text-muted d-block mb-1">Длительность</small>
                                <div class="me-2 mb-2">
                                    <span class="mb-0">{{ course.duration }}мин</span>
                                </div>
                                <small class="text-muted d-block mb-1">Всего групп</small>
                                <div class="me-2 mb-2">
                                    <span class="mb-0">{{ course.group_set.count }}</span>
                                </div>
                            </ul>
                          </div>
                        </div>
                      </div>
                    <div class="col-md-6 col-lg-4 order-2 mb-4">
                      <div class="card">
                        <div class="card-header d-flex align-items-center justify-content-between">
                          <h5 class="card-title m-0 me-2">Группы</h5>
                        </div>
                        <div class="card-body">
                          <ul class="p-0 m-0">
                             {% for group in groups %}
                             <li class="d-flex mb-4 pb-1">
                                <div class="avatar flex-shrink-0 me-3">
                                  <i class="bx bx-group"></i>
                                </div>
                                <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                                  <div class="me-2">
                                    <small class="text-muted d-block mb-1">{{ group.start_time }}</small>
                                    <h6 class="mb-0"><a href="{% url 'group-detail' group.id %}">{{ group.title }}</a></h6>
                                  </div>
                                  <div class="user-progress d-flex align-items-center gap-1">
                                    <h6 class="mb-0">{{ group.pupil_set.count }}</h6> <span class="text-muted"><i class='bx bx-face'></i></span>
                                  </div>
                                </div>
                              </li>
                             {% endfor %}
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 col-lg-4 order-2 mb-4">
                        <div class="nav-align-top mb-4">
                          <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                              <button type="button" class="nav-link active" role="tab" data-bs-toggle="tab" data-bs-target="#navs-top-home" aria-controls="navs-top-home" aria-selected="true">Студенты</button>
                            </li>
                            <li class="nav-item">
                              <button type="button" class="nav-link" role="tab" data-bs-toggle="tab" data-bs-target="#navs-top-profile" aria-controls="navs-top-profile" aria-selected="false">Преподаватели</button>
                            </li>
                          </ul>
                          <div class="tab-content">
                            <div class="tab-pane fade show active" id="navs-top-home" role="tabpanel">
                              <ul class="p-0 m-0">
                                {% for pupil in pupils %}
                                <li class="d-flex mb-4 pb-1">
                                   <div class="avatar flex-shrink-0 me-3">
                                     {% if pupil.image %}
                                     <img src="{{ pupil.image.url }}" alt="User" class="rounded">
                                     {% else %}
                                     <img src="{% static 'assets/img/avatars/5.png' %}" alt="User" class="rounded">
                                     {% endif %}
                                   </div>
                                   <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                                     <div class="me-2">
                                       <small class="text-muted d-block mb-1">+{{ pupil.phone }}</small>
                                       <h6 class="mb-0"><a href="{% url 'pupil-profile' pupil.id %}">{{ pupil.name }}</a></h6>
                                     </div>
                                     <div class="user-progress d-flex align-items-center gap-1">
                                       <h6 class="mb-0">{{ pupil.total_amount }}</h6> <span class="text-muted"><i class='bx bx-money'></i></span>
                                     </div>
                                   </div>
                                 </li>
                                {% endfor %}
                            </ul>
                            </div>
                            <div class="tab-pane fade" id="navs-top-profile" role="tabpanel">
                              <ul class="p-0 m-0">
                                {% for teacher in teachers %}
                                <li class="d-flex mb-4 pb-1">
                                   <div class="avatar flex-shrink-0 me-3">
                                     {% if teacher.image %}
                                     <img src="{{ teacher.image.url }}" alt="User" class="rounded">
                                     {% else %}
                                     <img src="{% static 'assets/img/avatars/5.png' %}" alt="User" class="rounded">
                                     {% endif %}
                                   </div>
                                   <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                                     <div class="me-2">
                                       <small class="text-muted d-block mb-1">+{{ teacher.phone }}</small>
                                       <h6 class="mb-0"><a href="{% url 'teacher-profile' teacher.id %}">{{ teacher.name }}</a></h6>
                                     </div>
                                   </div>
                                 </li>
                                {% endfor %}
                            </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                  </div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
    <div class="content-backdrop fade"></div>
</div>
{% endblock %}

templates/dashboard/course_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
      <h3>Курсы</h3>

      <div class="row">
        <div class="col-lg-2 mb-4 order-0">
          <button class="btn btn-dark" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasEnd" aria-controls="offcanvasEnd">Добавить</button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasEnd" aria-labelledby="offcanvasEndLabel" style="visibility: hidden;" aria-modal="true" role="dialog">
            <div class="offcanvas-header">
              <h5 id="offcanvasEndLabel" class="offcanvas-title">Добавление группы</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
              <div class="col-xl">
                <div class="card mb-4">
                  <div class="card-header d-flex justify-content-between align-items-center">
                  </div>
                  <div class="card-body">
                    <form method="post" action="" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="mb-3">
                        <label class="form-label" for="title">Постер</label>
                        <div class="input-group input-group-merge">
                          <span id="basic-icon-default-fullname2" class="input-group-text"><i class="bx bx-captions"></i></span>
                          {{ form.image }}
                        </div>
                      </div>
                      <div class="mb-3">
                        <label class="form-label" for="title">Название</label>
                        <div class="input-group input-group-merge">
                          <span id="basic-icon-default-fullname2" class="input-group-text"><i class="bx bx-captions"></i></span>
                          {{ form.title }}
                        </div>
                      </div>
                      <div class="mb-3">
                        <label class="form-label" for="duration">Длительность урока</label>
                        <div class="input-group input-group-merge">
                          <span id="basic-icon-default-phone2" class="input-group-text"><i class="bx bx-time"></i></span>
                          {{ form.duration }}
                        </div>
                      </div>
                      <div class="mb-3">
                        <label class="form-label" for="price">Цена</label>
                        <div class="input-group input-group-merge">
                          <span class="input-group-text"><i class='bx bx-money'></i></span>
                          {{ form.price }}
                        </div>
                      </div>
                      <button type="submit" class="btn btn-primary">Добавить</button>
                    </form>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>

      <div class="row">
        {% for course in courses %}
        <a href="{% url 'course-detail' course.id %}" class="col-sm-6 col-lg-4 mb-4 text-dark">
          <div class="card h-100">
            {% if course.image %}
            <img class="card-img-top" src="{{ course.image.url }}" alt="Card image cap">
            {% else %}
            <img class="card-img-top" src="{% static 'landing_assets/img/popular-course/p1.jpg' %}" alt="Card image cap">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ course.title }}</h5>
              <div class="d-flex align-items-center gap-4 justify-content-between">
                <div class="d-flex align-items-center gap-1">
                  <i class='bx bx-group'></i>
                  <p class="card-text">{{ course.group_set.count }}</p>
                </div>
                <div class="d-flex align-items-center gap-1">
                  <i class='bx bx-money' ></i>
                  <p class="card-text"><small class="text-muted">{{ course.price }}с</small></p>
                </div>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
    {% include 'includes/footer.html' %}
    <div class="content-backdrop fade"></div>
</div>
{% endblock %}

templates/dashboard/course_update.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="card mb-4">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">Редактирование курса</h5>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="d-flex gap-4">
                                <div class="mb-3">
                                    <label class="form-label" for="image">Постер</label>
                                      {{ form.image }}
                                  </div>
                                <div class="mb-3">
                                    <label class="form-label" for="basic-default-fullname">Название</label>
                                    {{ form.title }}
                                </div>
                                <div class="mb-3">
                                    <label class="form-label" for="basic-default-company">Длительность урока</label>
                                    {{ form.duration }}
                                </div>
                            </div>
                            <div class="mb-3 col-lg-1">
                                    <label class="form-label" for="basic-default-company">Цена</label>
                                    {{ form.price }}
                            </div>

                            <button type="submit" class="btn btn-primary">Применить изменения</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'includes/footer.html' %}


    <div class="content-backdrop fade"></div>
</div>
{% endblock %}

templates/dashboard/group_update.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row">
            <div class="col-12 mx-auto">
                <div class="card mb-4">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">Редактирование группы</h5>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="d-flex gap-4">
                                <div class="mb-3">
                                    <label class="form-label" for="basic-default-fullname">Название</label>
                                    {{ form.title }}
                                </div>
                                <div class="mb-3">
                                    <label class="form-label" for="basic-default-company">Курс</label>
                                    {{ form.course }}
                                </div>
                            </div>
                            <div class="d-flex gap-4">
                                <div class="mb-3">
                                    <label class="form-label" for="basic-default-company">Начало урока</label>
                                    {{ form.start_time }}
                                </div>
                                <div class="mb-3">
                                    <label class="form-label" for="basic-default-company">Аудитория</label>
                                    {{ form.room }}
                                </div>
                                <div class="mb-3">
                                    <label class="form-label" for="basic-default-company">Цвет для графика</label>
                                    {{ form.color }}
                                </div>
                            </div>
                            <div class="mb-3">
                                <label class="form-label" for="basic-default-company">Дни</label>
                                {{ form.days }}
                            </div>
                            
                            <button type="submit" class="btn btn-primary">Применить изменения</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'includes/footer.html' %}


    <div class="content-backdrop fade"></div>
</div>
{% endblock %}

templates/dashboard/lesson_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
      <div class="col-12 mx-auto">
        <div class="card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="mb-0">Форма Урока</h5>
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <div class="d-flex gap-4">
                <div class="mb-3">
                  <label class="form-label" for="basic-default-fullname">Название</label>
                  {{ form.title }}
                </div>
              </div>
              <div class="mb-3">
                {{ form.content }}
              </div>
              <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
          </div>
        </div>
      </div>
    </div>

  <!-- <script>
    $(document).ready(function() {
      $('.summernote').summernote();  // Используйте класс 'summernote' для Summernote
    });
  </script> -->
  </div>

  {% include 'includes/footer.html' %}


  <div class="content-backdrop fade"></div>
</div>
{% endblock %}