apps/user/urls.py
from django.urls import path
from .views  import *

urlpatterns = [
    # Profiles
    path('pupil-profile/<str:pk>/', pupil_profile, name='pupil-profile'),
    path('teacher-profile/<str:pk>/', teacher_profile, name='teacher-profile'),
    path('operator-profile/<str:pk>/', operator_profile, name='operator-profile'),
    # List
    path('teacher-pupils/', teacher_pupils, name='teacher-pupils'),
    path('teacher-lessons/<str:pk>/', teacher_lessons, name='teacher-lessons'),
    path('teacher-groups/', teacher_groups, name='teacher-groups'),
    path('pupil-groups/', pupil_groups, name='pupil-groups'),
    path('pupil-lessons/<str:pk>/', pupil_lessons, name='pupil-lessons'),
    # Profile Login
    path('login/', login_page, name='login'),
    path('profile/<str:pk>/', profile, name='profile'),
    path('profile-access/<str:pk>/', profile_access, name='profile-access'),
    path('logout/', logout_user, name='logout'),
    # Other
    path('check-detail/<str:pk>/', check_detail, name='check-detail'),
    path('send-to-whatsapp/<str:pk>/', send_to_whatsapp, name='send-to-whatsapp'),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.dashboard.urls')),
    path('account/', include('apps.user.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/user/models.py
from django.db import models
from apps.dashboard.models import Group, Course
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=140, null=True)
    STATUS = (
        ('1', 'Админ'),
        ('2', 'Студент'),
        ('3', 'Преподаватель'),
        ('4', 'Администратор')
    )
    role = models.CharField(null=True, choices=STATUS, max_length=140, default='1')
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []


class Lesson(models.Model):
    title = models.CharField(max_length=140)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    group_access = models.ManyToManyField(Group, blank=True)
    content = models.TextField(null=True, blank=True)
    access = models.BooleanField(null=True, blank=True, default=False)


    
    def __str__(self):
        return self.title


class Question(models.Model):
    lesson=models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True, blank=True)
    SKILLS = (
        ('vocabulary', 'Vocabulary'),
        ('grammary', 'Grammary'),
        ('speaking', 'Speaking'),
        ('reading', 'Reading'),
        ('listening', 'Listening'),
    )
    skill = models.CharField(max_length=80, null=True, choices=SKILLS)
    title = models.CharField(max_length=150, null=True)
    marks=models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=20, null=True)
    is_correct = models.BooleanField(default=False ,verbose_name='Правильно')

    def __str__(self):
        return self.title


class TestResult(models.Model):
    pupil = models.ForeignKey('Pupil', on_delete=models.CASCADE, null=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, null=True)
    questions = models.ManyToManyField(Question)
    total_correct_answers = models.IntegerField(null=True)
    total_questions = models.IntegerField(null=True)
    
    vocabulary_score = models.IntegerField(null=True, blank=True, default='0')
    listening_score = models.IntegerField(null=True, blank=True, default='0')
    reading_score = models.IntegerField(null=True, blank=True, default='0')
    grammary_score = models.IntegerField(null=True, blank=True, default='0')
    speaking_score = models.IntegerField(null=True, blank=True, default='0')


    def __str__(self):
        return self.pupil.name


class Operator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='profile_photos', null=True, blank=True)
    phone = models.CharField(max_length=12, default='996')
    group = models.ManyToManyField(Group)
    password = models.CharField(max_length=20, null=True, default=' ')

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='profile_photos', null=True, blank=True)
    phone = models.CharField(max_length=12, default='996')
    group = models.ManyToManyField(Group)
    payment = models.IntegerField(null=True)
    password = models.CharField(max_length=20, null=True, default=' ')

    def __str__(self):
        return self.name

    @property
    def group_pupil_percentage(self):
        total_pupils = 0
        total_percentage = 0
        
        for group in self.group.all():
            pupils = group.pupil_set.all()
            total_pupils += len(pupils)
            total_percentage += sum([pupil.total_percentage for pupil in pupils])
        
        return round(total_percentage / total_pupils) if total_pupils else 0

class Pupil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='profile_photos', null=True, blank=True)
    phone = models.CharField(max_length=12, default='996')
    group = models.ManyToManyField(Group)
    password = models.CharField(max_length=20, null=True, default=' ')


    def __str__(self):
        return self.name
    

    @property
    def total_amount(self):
        transactions = self.transaction_set.all()
        total = sum([item.amount for item in transactions])
        return total
    
    @property
    def total_score(self):
        answers = self.testresult_set.all()
        total = sum([item.total_correct_answers for item in answers])
        return total
    
    @property
    def total_questions(self):
        questions = self.testresult_set.all()
        total = sum([item.total_questions for item in questions])
        return total
    
    @property
    def total_percentage(self):
        try:
            return round((self.total_score / self.total_questions) * 100)
        except:
            return  0

    def skill_percentage(self, skill):
        skill_questions = TestResult.objects.filter(
            pupil=self,
            questions__skill=skill
        ).count()
        correct_answers = TestResult.objects.filter(pupil=self)
        total_score = sum(getattr(item, f'{skill}_score') for item in correct_answers)

        if skill_questions != 0:
            skill_percentage = (total_score / skill_questions) * 100
        else:
            skill_percentage = 0

        return round(skill_percentage)

    @property
    def vocabulary_percentage(self):
        return self.skill_percentage('vocabulary')

    @property
    def grammary_percentage(self):
        return self.skill_percentage('grammary')

    @property
    def reading_percentage(self):
        return self.skill_percentage('reading')

    @property
    def speaking_percentage(self):
        return self.skill_percentage('speaking')

    @property
    def listening_percentage(self):
        return self.skill_percentage('listening')


class Attendance(models.Model):
    pupils = models.ManyToManyField(Pupil)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.lesson.title} ({self.date})'


class Transaction(models.Model):
    pupil = models.ForeignKey(Pupil, on_delete=models.SET_NULL, null=True)
    amount = models.IntegerField()
    comment = models.TextField(max_length=140)
    created = models.DateField(auto_now_add=False)


class Report(models.Model):
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE, null=True)
    TYPE = (
        ('plus', 'Приход'),
        ('minus', 'Расход')
    )

    title = models.CharField(max_length=140)
    price = models.FloatField()
    type = models.CharField(choices=TYPE, max_length=40)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/user/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import requests
from django.http import HttpResponse

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

# Login Page
def login_page(request):
    page = 'login'
    ip = get_client_ip(request)
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Такого пользователя не существует')

    context = {'page': page}
    return render(request, 'user/login.html', context)


# Logout User
def logout_user(request):
    logout(request)
    return redirect('home')

# Operator
@login_required(login_url='login')
def operator_profile(request, pk):
    if not request.user.is_superuser:
        return redirect('home')
        
    operator = Operator.objects.get(id=pk)

    form = OperatorForm(instance=operator)
    if request.method == 'POST':
        form = OperatorForm(request.POST, request.FILES, instance=operator)
        if form.is_valid():
            form.save()
            return redirect('operator-profile', pk=pk)
    
    if request.method == 'POST' and 'delete' in request.POST:
        operator.delete()
        return redirect('operator-list')
    
    context = {
        'operator': operator,
        'form': form,
    }
    return render(request, 'user/operator_profile.html', context)


# Pupil
@login_required(login_url='login')
def pupil_profile(request, pk):
    if request.user.role == '2':
        return redirect('home')
        
    
    pupil = Pupil.objects.get(id=pk)
    get_amount_total = Transaction.objects.filter(pupil__id=pk)
    total  = 0
    for i in get_amount_total:
        total += i.amount

    form = PupilForm(instance=pupil)
    if request.method == 'POST':
        form = PupilForm(request.POST, request.FILES, instance=pupil)
        if form.is_valid():
            form.save()
            return redirect('pupil-profile', pk=pk)
    
    if request.method == 'POST' and 'delete' in request.POST:
        pupil.delete()
        return redirect('pupil-list')

    form2 = TransactionForm()
    if request.method == 'POST' and 'transaction' in request.POST:
        form2 = TransactionForm(request.POST)
        if form2.is_valid():
            form2.instance.pupil = pupil
            form2.save()
            return redirect('pupil-profile', pk=pk)

    transactions = Transaction.objects.filter(pupil=pupil).order_by('-id')

    

    context = {
        'pupil': pupil,
        'form': form,
        'form2': form2,
        'get_amount_total': total,
        'transactions': transactions,
    }
    return render(request, 'user/pupil_profile.html', context)

@login_required(login_url='login')
def pupil_groups(request):
    if request.user.role != '2':
        return redirect('home')
    groups = Group.objects.filter(pupil=request.user.pupil)

    context = {
        'groups': groups
    }
    return render(request, 'user/pupil_groups.html', context)

@login_required(login_url='login')
def pupil_lessons(request, pk):
    if request.user.role != '2':
        return redirect('home')
    pupil = Pupil.objects.get(user=request.user)
    groups = Group.objects.filter(pupil=pupil)
    group = Group.objects.get(id=pk)

    lessons = Lesson.objects.filter(group_access__in=groups)
    context = {
        'lessons': lessons,
        'group': group
    }
    return render(request, 'user/pupil_lessons.html', context)


# Teacher
@login_required(login_url='login')
def teacher_profile(request, pk):
    if not request.user.is_superuser:
        return redirect('home')
        
    teacher = Teacher.objects.get(id=pk)
    # total_payment = teacher.group.pupil_set.count() * teacher.payment

    form = TeacherForm(instance=teacher)
    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect('teacher-profile', pk=pk)
    
    if request.method == 'POST' and 'delete' in request.POST:
        teacher.delete()
        return redirect('teacher-list')
    

    group = Group.objects.filter(teacher=teacher)
    # pupils = Pupil.objects.filter(group=group)

    context = {
        'teacher': teacher,
        'form': form,
        # 'total_payment': total_payment,
        # 'pupils': pupils,
    }
    return render(request, 'user/teacher_profile.html', context)

@login_required(login_url='login')
def teacher_pupils(request):
    teacher = Teacher.objects.get(user=request.user)
    group = Group.objects.filter(teacher=teacher)
    pupils = Pupil.objects.filter(group__in=group)
    context = {
        'pupils': pupils,
        'teacher': teacher,
    }
    return render(request, 'user/teacher_pupils.html', context)

@login_required(login_url='login')
def teacher_groups(request):
    if request.user.role != '3':
        return redirect('home')
    groups = Group.objects.filter(teacher=request.user.teacher)

    context = {
        'groups': groups
    }
    return render(request, 'user/teacher_groups.html', context)

@login_required(login_url='login')
def teacher_lessons(request, pk):
    if request.user.role != '3':
        return redirect('home')
    teacher = Teacher.objects.get(user=request.user)
    group = Group.objects.get(id=pk)

    lessons = Lesson.objects.filter(course__group=group).distinct()
    context = {
        'lessons': lessons,
        'group': group
    }
    return render(request, 'user/teacher_lessons.html', context)


# Profile
@login_required(login_url='login')
def profile(request, pk):
    user = User.objects.get(id=pk)
    if request.user == user and request.user.role == '3':
        teacher = Teacher.objects.get(user=user)
        total_payment = teacher.group.pupil_set.count() * teacher.payment
        teacher_total_payment = total_payment * teacher.group.pupil_set.count()
        context = {
        'user': user,
        'total_payment': total_payment,
        'teacher': teacher,
        'teacher_total_payment': teacher_total_payment
        }
        return render(request, 'user/profile.html', context)
    if request.user == user and request.user.role == '2':
        pupil = Pupil.objects.get(user=user)
        get_amount_total = Transaction.objects.filter(pupil=pupil)
        total  = 0
        for i in get_amount_total:
            total += i.amount
        context = {
        'user': user,
        'pupil': pupil,
        'get_amount_total': total
        }
        return render(request, 'user/profile.html', context)
    if request.user == user and request.user.role == '1':
        user = User.objects.get(id=pk)
        context = {
        'user': user,
        }
        return render(request, 'user/profile.html', context)
    context = {
        'user': user,
        }
    return render(request, 'user/profile.html', context)
    
@login_required(login_url='login')
def profile_access(request, pk):
    user = User.objects.get(id=pk)
    if request.user == user and request.user.role == '3':
        teacher = Teacher.objects.get(user=user)
        context = {
        'user': user,
        'teacher': teacher
        }
        return render(request, 'user/profile_access.html', context)
    if request.user == user and request.user.role == '2':
        pupil = Pupil.objects.get(user=user)
        context = {
        'user': user,
        'pupil': pupil
        }
        return render(request, 'user/profile_access.html', context)
    if request.user == user and request.user.role == '1':
        user = User.objects.get(id=pk)
        context = {
        'user': user,
        }
        return render(request, 'user/profile_access.html', context)


# Check
def check_detail(request, pk):
    transaction = Transaction.objects.get(id=pk)
    pupil = transaction.pupil
    context = {
        'transaction': transaction,
        'pupil': pupil
        }
    return render(request, 'user/check_detail.html', context)


def send_to_whatsapp(request, pk):
    transaction = Transaction.objects.get(id=pk)
    message = f"Здравствуйте! Ваш чек: {transaction.amount} СОМ, для {transaction.pupil.name}"
    

    whatsapp_api_url = "https://api.whatsapp.com/send"
    params = {
        "phone": f"{transaction.pupil.phone}",
        "text": message,
    }
    response = requests.get(whatsapp_api_url, params=params)
    
    if response.status_code == 200:
        return HttpResponse("Сообщение отправлено на WhatsApp")
    else:
        return HttpResponse("Произошла ошибка при отправке сообщения")

templates/user/check_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row">
            <div class="col-md-12">
                <div class="card mx-auto col-lg-4 py-2 px-2">
                    <h5 class="card-header">
                        Чек
                    </h5>
                    <div class="card-body">
                        <form id="formAccountSettings" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <span>Имя</span>
                                <strong>{{ pupil.name }}</strong>
                                <span>Сумма</span>
                                <strong>{{ transaction.amount }}</strong>
                                <span>ID</span>
                                <strong>{{ transaction.id }}</strong>
                                <span>Комментарий</span>
                                <strong>{{ transaction.comment }}</strong>
                            </div>
                            <div class="mt-2">
                                <button type="submit" class="btn btn-icon btn-outline-secondary me-2"><i
                                        class='bx bxs-printer'></i></button>
                                <a class="btn btn-icon btn-outline-success"
                                    href="https://api.whatsapp.com/send?phone={{ transaction.pupil.phone }}&text=Добрый день! Мы рады предоставить вам информацию о платеже за обучение в MyAcademy. По данному чеку видно, что студент {{ transaction.pupil.name }} внёс сумму в размере {{ transaction.amount }} сом. Примечание к платежу: {{ transaction.comment }}."
                                    target="_blank"><i class='bx bxl-whatsapp'></i></a>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
    {% include 'includes/footer.html' %}
    <div class="content-backdrop fade"></div>
</div>
{% endblock %}

templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>My Academy</title>
    
    <meta name="description" content="Курсы разработки роботов!">
    <meta name="keywords" content="academy, myacademy, my-academy, roboacademy, robo academy">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon/favicon.ico' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&amp;display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{%  static 'assets/vendor/fonts/boxicons.css' %}">
    
    

    <!-- Core CSS -->
    <link rel="stylesheet" href="{%  static 'assets/vendor/css/core.css' %}" class="template-customizer-core-css">
    <link rel="stylesheet" href="{%  static 'assets/vendor/css/theme-default.css' %}" class="template-customizer-theme-css">
    <link rel="stylesheet" href="{%  static 'assets/css/demo.css' %}">

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{%  static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}">
    
    

    <!-- Page CSS -->
    <!-- Page -->
<link rel="stylesheet" href="{%  static 'assets/vendor/css/pages/page-auth.css' %}">
    <!-- Helpers -->
    <script src="{%  static 'assets/vendor/js/helpers.js' %}"></script><style type="text/css">
.layout-menu-fixed .layout-navbar-full .layout-menu,
.layout-page {
  padding-top: 0px !important;
}
.content-wrapper {
  padding-bottom: 0px !important;
}</style>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{%  static 'assets/js/config.js' %}"></script>
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async="async" src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
    <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', 'GA_MEASUREMENT_ID');
    </script>
    <!-- Custom notification for demo -->
    <!-- beautify ignore:end -->

</head>

<body cz-shortcut-listen="true">

  <!-- Content -->

<div class="container-xxl">
  <div class="authentication-wrapper authentication-basic container-p-y">
    <div class="authentication-inner">
      <!-- Register -->
      <div class="card">
        <div class="card-body">
          <!-- Logo -->
          <div class="app-brand justify-content-center">
            <a href="{% url 'home' %}" class="app-brand-link gap-2">
              <img src="{% static 'assets/img/logo/myacademy_logo.png' %}" style=" height: 80px;" alt="">
            </a>
          </div>
          <!-- /Logo -->
          <h4 class="mb-2">Добро пожаловать в My Academy! 👋</h4>
          <span class="mb-4">Пожалуйста войдите в свой аккаунт чтобы продолжить работу!</span>
          <p class="text-warning">Если вы преподаватель или студент, логин и пароль выдаются администратором</p>
          <form id="formAuthentication" class="mb-3" method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="username" class="form-label">Логин</label>
              <input type="text" class="form-control" id="username" name="username" placeholder="Введите ваш логин" autofocus="">
            </div>
            <div class="mb-3 form-password-toggle">
              <div class="d-flex justify-content-between">
                <label class="form-label" for="password">Пароль</label>
                <a href="auth-forgot-password-basic.html">
                  <small>Забыли пароль?</small>
                </a>
              </div>
              <div class="input-group input-group-merge">
                <input type="password" id="password" class="form-control" name="password" placeholder="············" aria-describedby="password">
                <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
              </div>
            </div>

            <div class="mb-3">
              <button class="btn btn-primary d-grid w-100" type="submit">Войти</button>
            </div>
            {% if messages %}
            <div class="alert alert-danger" role="alert">
              {% for message in messages %}
                {{ message }}
                {% endfor %}
            </div>
            {% endif %}
          </form>

        </div>
      </div>
    </div>
  </div>
</div>



  <script src="{%  static 'assets/vendor/libs/jquery/jquery.js' %}"></script>
  <script src="{%  static 'assets/vendor/libs/popper/popper.js' %}"></script>
  <script src="{%  static 'assets/vendor/js/bootstrap.js' %}"></script>
  <script src="{%  static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
  <script src="{%  static 'assets/vendor/js/menu.js' %}"></script>
  <script src="{%  static 'assets/js/main.js' %}"></script>
  <script async="" defer="" src="https://buttons.github.io/buttons.js"></script>
</body></html>

templates/user/operator_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
  <div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
      <div class="col-md-5">
        <div class="card mb-4 ">
          <div class="card-body">
            <div class="mb-4 text-center">
              <div class="wd-150 ht-150 mx-auto mb-3 position-relative">
                <div class="avatar-image wd-150 ht-150">
                  {% if operator.image %}
                  <img src="{{ operator.image.url }}" alt="" width="255" height="255" style="object-fit: cover; object-position: center; border-radius: 50%;">
                  {% else %}
                  <img src="{% static 'assets/img/avatars/5.png' %}" alt="" width="255" height="255" style="object-fit: cover; object-position: center; border-radius: 50%;">
                  {% endif %}
                </div>
                <div class="wd-10 ht-10 text-success rounded-circle position-absolute translate-middle"
                  style="top: 76%; right: 10px">
                  <i class="bi bi-patch-check-fill"></i>
                </div>
              </div>
              <div class="mb-4">
                <span class="fs-14 fw-bold d-block">{{ operator.name }}</span>
                <span class="fs-12 fw-normal text-muted d-block">+{{ operator.phone }}</span>
              </div>
            </div>
            <ul class="list-unstyled mb-4">
              <li class="hstack justify-content-between mb-4">
                <span class="text-muted fw-medium hstack gap-3"><i class="feather-map-pin"></i>Логин:</span>
                <span class="float-end">{{ operator.user.username }}</span>
              </li>
              <li class="hstack justify-content-between mb-4">
                <span class="text-muted fw-medium hstack gap-3"><i class="feather-phone"></i>Пароль:</span>
                <span class="float-end">{{ operator.password }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>


      <div class="col-md-6 h-100">
        <div class="nav-align-top mb-4">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <button type="button" class="nav-link active" role="tab" data-bs-toggle="tab"
                data-bs-target="#navs-top-home" aria-controls="navs-top-home" aria-selected="true">Аккаунт</button>
            </li>

          </ul>
          <div class="tab-content">
            <div class="tab-pane fade active show" id="navs-top-home" role="tabpanel">
              <div class="card-body">
                <form id="formAccountSettings" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row">
                    <div class="mb-3 col-md-6">
                      <label for="group" class="form-label">Изображение</label>
                      {{ form.image }}
                    </div>
                    <div class="mb-3 col-md-6">
                      <label for="name" class="form-label">Полное имя</label>
                      {{ form.name }}
                    </div>
                    <div class="mb-3 col-md-6">
                      <label for="phone" class="form-label">Контактный номер</label>
                      {{ form.phone }}
                    </div>
                  </div>
                  <div class="mt-2">
                    <button type="submit" class="btn btn-primary me-2">Сохранить изменения</button>
                    <a href="{% url 'operator-list' %}" class="btn btn-outline-secondary">Отменить</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>




    <div class="card">
      <h5 class="card-header">Удалить аккаунт</h5>
      <div class="card-body">
        <div class="mb-3 col-12 mb-0">
          <div class="alert alert-warning">
            <h6 class="alert-heading fw-bold mb-1">Вы уверены что хотите удалить этот аккаунт?</h6>
            <p class="mb-0">Удаление аккаунта необратимо.</p>
          </div>
        </div>
        <form id="formAccountDeactivation" method="post">
          {% csrf_token %}
          <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" name="delete" id="accountActivation" required>
            <label class="form-check-label" for="accountActivation">Я подтверждаю удаление этого аккаунта</label>
          </div>
          <button type="submit" class="btn btn-danger deactivate-account">Удалить аккаунт</button>
        </form>
      </div>
    </div>
  </div>
  {% include 'includes/footer.html' %}


  <div class="content-backdrop fade"></div>
</div>
{% endblock %}

templates/user/pupil_lessons.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="mb-4 mb-xl-0">
            <small class="text-light fw-semibold">Уроки</small>
            <div class="demo-inline-spacing mt-3">
                <div class="d-flex gap-4">
                   <div class="col-4">
                    <div class="card-body">
                        <h4>{{ group.title|truncatewords:4 }}</h4>
                        <ol class="list-group list-group-numbered">
                        {% for lesson in group.course.lesson_set.all %}
                            {% if lesson.access and group in lesson.group_access.all %}
                            <li class="list-group-item"><a href="{% url 'lesson-detail' lesson.id %}"><strong class="text-dark">{{ lesson.title }}</strong></a></li>
                            {% endif %}
                        {% endfor %}
                        </ol>
                    </div>
                   </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
    <div class="content-backdrop fade"></div>
</div>
{% endblock %}